- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false # not confidential
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
     msg: "Given number {{ number }} is less than 10"